In [1]:
import sys
import numpy as np
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
#filename = sys.argv[1]
filename = "../../3dpcp_book_codes/3rdparty/Open3D/examples/test_data/bathtub_0154.ply"

print("Loading a point cloud from", filename)
pcd = o3d.io.read_point_cloud(filename)

print(pcd)
print(np.asarray(pcd.points))

o3d.visualization.draw_geometries([pcd])

Loading a point cloud from ../../3dpcp_book_codes/3rdparty/Open3D/examples/test_data/bathtub_0154.ply
PointCloud with 1494 points.
[[ -9208.08007812  19354.84960938  -6295.04980469]
 [ -1696.69995117  -3551.25        -6295.04980469]
 [  9129.29980469  19354.84960938  -6295.04980469]
 ...
 [ 14763.79980469  33464.55078125  13005.90039062]
 [ 14763.79980469 -33464.55078125   9068.90039062]
 [ 14763.79980469  33464.55078125   9068.90039062]]
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.
